### PR TITLE
add jar for the depict module

### PR DESCRIPTION
**Pull request by zachcp**
depict doesn't seem to be packages as part of the core cdk Jar but offers a useful API for making images that would be beneficial to rCDK. its a small jar and I would argue that it warrants inclusion. Also it build on my local machine.

zach cp

### CODE REVIEW

**Comment by rajarshi** [comment]
If the intention is to make this available in `rcdk`, you should edit `build.xml` to ensure that it gets copied in to the appropriate `rcdk` folder. Also, do you plan to include code that makes use of this JAR file? Currently the depiction methods don't, but if you're planning to update them or add new ones, it'd help justify inclusion

**Comment by zachcp** [comment]
I may have done this incorrectly. My intention was to have this as part of the rdcklibs JARs. Looking a second time it seems these are packaged into rCDK as well. Is that right? I don't think these necessarily need to be in rCDK but I think they should definitely be available in rcdklib as that is the primary means of using CDK from R.  I am interested in using the Depiction module to write some helper functions to generate images from R.  The new Depiction module gives a lot of control over appearance and output. I could imagine a module that wraps these functions although its simple enough you might be able to do everything via `$` in Java. But I think its worthy of inclusion and will help in any way I can.

**Comment by rajarshi** [comment]
Ah ok. in that case you should probably add it to the `rcdklibs` package and not here. Also ensure you als o updated the R code in `rcdklibs` so this JAR is added to the classpath

**Comment by zachcp** [comment]
closing this in favor of #33

**Pull request closed without merging**
